### ISSUE TITLE
Wrong console function

### ISSUE THREAD

**Issue by lankybox02** [JaydenDev/BracketsJS#25]
https://github.com/JaydenDev/BracketsJS/blob/51327d709fec3392c8ecee85df4fda4004ea069c/src/index.js#L133

Why does this need to be a warning?

**Comment by JaydenDev** [comment]
> https://github.com/JaydenDev/BracketsJS/blob/51327d709fec3392c8ecee85df4fda4004ea069c/src/index.js#L133
> 
> Why does this need to be a warning?

Someone else rewrote the entire script in a PR I think, replaced my methods with better ones. Ask @dinonull.

**Comment by lankybox02** [comment]
> Someone else rewrote the entire script in a PR I think, replaced my methods with better ones. Ask @dinonull. I'll fix it soon. What do I use other than warning?

`log` or `info`

**Comment by JaydenDev** [comment]
alright. I did complete this already using log.
