### ISSUE TITLE
Line 54 

### ISSUE THREAD

**Issue by Chiroyce1** [JaydenDev/BracketsJS#3]
https://github.com/JaydenDev/BracketsJS/blob/9f04781db059934f7bc2dd74b55456cd984b0dc9/library.js#L54

Isn't it meant to be
```js
 if (bypassFileExtension == true) { 
```
or even better
```js
 if (bypassFileExtension) { 
```

**Comment by JaydenDev** [comment]
Well it _works_? I'll make that change eventually, but it'll have a low priority.

**Comment by JaydenDev** [comment]
Fixed with commit [87115bb](https://github.com/JaydenDev/BracketsJS/commit/87115bb64e1ee777cb77d6ee6daaf450bc197131)

**Comment by Chiroyce1** [comment]
You broke it even more now, the code simply won't work and will throw `Uncaught SyntaxError: Unexpected token '=='`, you only have to change line 54, nothing else. 

`=` is to assign data to a variable, `==` is for comparing a variable to another value.

So in line 52, you use `=` to let JS know that you're assigning a value to a variable and in line 54, you ask JS to compare the `bypassFileExtension` variable to `true` (or any value that will evaluate to 1 or true)

**Comment by JaydenDev** [comment]
fixed completely now
